spring:
  application:
    name: Student_Management

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StudentManagementDB;encrypt=true;trustServerCertificate=true
    username: sms_user
    password: smsuser@123

  jpa:
    hibernate:
      ddl-auto: validate

    liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml