spring:
  application:
    name: Student_Management

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StudentManagementDB;encrypt=true;trustServerCertificate=true
    username: sms_user
    password: smsuser@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true