IF DB_ID(N'$(DB_NAME)') IS NULL
BEGIN
    CREATE DATABASE [$(DB_NAME)];
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'$(DB_USERNAME)')
BEGIN
    CREATE LOGIN [$(DB_USERNAME)] WITH PASSWORD = N'$(DB_PASSWORD)', CHECK_POLICY = ON;
END;
GO

USE [$(DB_NAME)];
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'$(DB_USERNAME)')
BEGIN
    CREATE USER [$(DB_USERNAME)] FOR LOGIN [$(DB_USERNAME)];
    ALTER ROLE db_owner ADD MEMBER [$(DB_USERNAME)];
END;
GO
